export function headlessWorkflowSource(): string {
  return [
    'import { artifactRefJsonSchema } from "@dromio/workflow/product";',
    representativeWorkflowSource(),
    'if (artifactRefJsonSchema.type !== "object") throw new Error("missing product runtime export");',
  ].join("\n");
}

export function representativeWorkflowSource(): string {
  return [
    'import { step, workflow } from "@dromio/workflow";',
    'import { z } from "zod";',
    '',
    'const greet = step({',
    '  id: "greet",',
    '  input: { name: z.string() },',
    '  output: { message: z.string() },',
    '  run: ({ input }) => ({ message: `Hello, ${input.name}!` }),',
    '});',
    '',
    'const greetingWorkflow = workflow({',
    '  catalog: [greet],',
    '  document: {',
    '    edges: [',
    '      { id: "trigger-to-greet", source: "trigger", target: "greet" },',
    '      { id: "greet-to-end", source: "greet", target: "end" },',
    '    ],',
    '    end: { id: "end", output: { message: { jsonSchema: { type: "string" } } }, type: "result" },',
    '    id: "greeting-workflow",',
    '    nodes: [{ catalogItemId: greet.id, id: "greet" }],',
    '    trigger: { id: "trigger", input: { name: { jsonSchema: { type: "string" } } }, type: "manual" },',
    '    version: 1,',
    '  },',
    '});',
    '',
    'const session = await greetingWorkflow.start({ name: "Dromio" });',
    'if (session.status !== "completed" || session.state.message !== "Hello, Dromio!") {',
    '  throw new Error(`Unexpected workflow result: ${JSON.stringify(session.state)}`);',
    '}',
    'console.log(session.state.message);',
    '',
    'const research = step.delegate({',
    '  capabilities: ["browser", "search"],',
    '  context: ({ input }) => ({ topic: input.topic }),',
    '  id: "research",',
    '  input: { topic: z.string() },',
    '  instructions: ({ input }) => `Research ${input.topic}`,',
    '  output: { report: z.string() },',
    '});',
    '',
    'const researchWorkflow = workflow({',
    '  catalog: [research],',
    '  document: {',
    '    edges: [',
    '      { id: "trigger-to-research", source: "trigger", target: "research" },',
    '      { id: "research-to-end", source: "research", target: "end" },',
    '    ],',
    '    end: { id: "end", output: { report: { jsonSchema: { type: "string" } } }, type: "result" },',
    '    id: "research-workflow",',
    '    nodes: [{ catalogItemId: research.id, id: "research" }],',
    '    trigger: { id: "trigger", input: { topic: { jsonSchema: { type: "string" } } }, type: "manual" },',
    '    version: 1,',
    '  },',
    '  input: { topic: z.string() },',
    '  output: { report: z.string() },',
    '});',
    '',
    'const delegated = await researchWorkflow.start({ topic: "Dromio" });',
    'const handoff = delegated.pendingHooks[0];',
    'if (delegated.status !== "waiting" || handoff?.kind !== "handoff_requested") {',
    '  throw new Error(`Unexpected delegated workflow state: ${delegated.status}`);',
    '}',
    'await delegated.resumeHook({ token: handoff.token, value: { report: "Verified" } });',
    'const completedDelegation = delegated.snapshot();',
    'if (completedDelegation.status !== "completed" || delegated.state.report !== "Verified") {',
    '  throw new Error(`Unexpected delegated result: ${JSON.stringify(delegated.state)}`);',
    '}',
    'console.log(delegated.state.report);',
    '',
  ].join("\n");
}
