export const packageDirectories = [
  "packages/protocols",
  "packages/execution",
  "packages/thread/service",
  "packages/trigger",
  "packages/workflow/canvas-protocol",
  "packages/workflow/kernel",
  "packages/room/protocol",
  "packages/shell/chat-shell-ui",
  "packages/sdk",
] as const;

export const canonicalPackageName = "@dromio/workflow";

/**
 * The eight packages supplied by the Kernel Version Packages train for the
 * Workflow 0.2.7 release. These are artifact identities, not source mirrors:
 * a rehearsal must consume the tarballs and manifest generated by Kernel #41.
 */
export const kernelFoundationPackages = [
  {
    integrity: "sha512-qTP6DBx+A0Mm/4bcFPm2J/pb/i1kkFhz7VjXDP5IzT/MUJukwvXUojkLohcj8G25AZjEO0+oazzYctskdjTfjg==",
    name: "@dromio/chat-shell-ui",
    shasum: "3270dc897d8f9db33d261c52bbd96d8dc36838a5",
    version: "0.2.0",
  },
  {
    integrity: "sha512-QagpAI37h8Tf8b3yd0oHkwQvlc+lNuhb1MRKy8M3iNUD3d9z3aMSoHo31HW1M8MdrqKrLs4i+lcalRezsMPf6A==",
    name: "@dromio/execution",
    shasum: "d844a7399220aa7b1ef99ba93ee0255e1dc3fd2b",
    version: "0.1.43",
  },
  {
    integrity: "sha512-1r1f7WyFzSxTjB7vyt1ARakUcqHZkVN+PKgQsqdR5i1yR4CTkjeUcgMRCQIZ0Dk9+u4VZvNEur5i/QoahzfOew==",
    name: "@dromio/protocols",
    shasum: "d8b81e08b819d2796a702d834c8d77bdd84d4f59",
    version: "0.3.0",
  },
  {
    integrity: "sha512-W0MwGBGkplC2eUNXansIpESm/y61oY5ouAD7bJZQYFwCU3KdtF+5ENSLmmUaDJO2+1zTj9GNgbKtHM05sGxPeg==",
    name: "@dromio/thread-service",
    shasum: "48f7c3cfd75154a2e647fc1510a6c1f9fda2c36c",
    version: "0.3.0",
  },
  {
    integrity: "sha512-m+xUXYtAM5j6EQhWcoxKPjwW9EE+VKzXVmb8Cqu8KXLVDkC9cUHnos2qFoq76Rl3nrmehNruZyvyPM+XwssSdg==",
    name: "@dromio/trigger",
    shasum: "4b3bb4e048283409e32ec0dc6dcd956e0db7176e",
    version: "0.1.45",
  },
  {
    integrity: "sha512-UeFFlHGOK8KNVI4tW61iFjc+3tSnDNDyjYDpO1D+lwhrMJ8BU8aynAq252Spn3SuxXUyrmAFS4u7edTWauMSQg==",
    name: "@dromio/workflow-canvas-protocol",
    shasum: "29aa5ce61828d7803be4063130184cb49536a242",
    version: "0.1.4",
  },
  {
    integrity: "sha512-bQ88bw4N+LIrp32jmLqtSkw8wKXZTuCNyu1EoRTatDE7e9AHOZKkUhwdKPoD3AylHcP06v/xmjKzj2NY334Wpw==",
    name: "@dromio/workflow-kernel",
    shasum: "fcbb4ad6c4978ca703e88ca7c28cdcc1d24ab154",
    version: "0.1.8",
  },
  {
    integrity: "sha512-F67gYVRXsgni2gmlucTx/6z6agZW+hAwRbHfUjQf1Zz5+0iLdJxxjcXB3f4p3UFMUS+8Ik2ncKMZuBhPJ1C2hQ==",
    name: "@dromio/workflow-room-protocol",
    shasum: "611b66db631679cdee0bb282fae6d7e000cbf174",
    version: "0.1.46",
  },
] as const;

export function selectCanonicalPublishTarget<T extends { readonly name: string }>(
  items: readonly T[],
): readonly T[] {
  const targets = items.filter((item) => item.name === canonicalPackageName);
  if (targets.length !== 1) {
    throw new Error(
      `The release manifest must contain exactly one ${canonicalPackageName} publish target; found ${targets.length}.`,
    );
  }
  return targets;
}
