import { ExecutionService, type ExecutionAttempt, type ExecutionRun } from "@dromio/execution";
import { TriggerService } from "@dromio/trigger";
import type { EnqueueScheduledTriggerOccurrenceInput, EnqueueTriggerInput, EnqueueTriggerResult, TriggerDescriptor, TriggerJobFilter, TriggerJobSnapshot } from "./types.js";

export class CanonicalTriggerExecutionFacade {
  constructor(private readonly options: { readonly tenantId: string; readonly applicationId: string; readonly triggers: TriggerService; readonly execution: ExecutionService; getTrigger(id: string): Promise<TriggerDescriptor> }) {}
  async enqueue(input: EnqueueTriggerInput): Promise<EnqueueTriggerResult> { const descriptor = await this.define(input.triggerId); const key = input.idempotencyKey ?? crypto.randomUUID(); const receipt = await this.options.triggers.occur({ triggerId: canonicalId(this.options, descriptor.id), type: triggerType(descriptor), tenantId: this.options.tenantId, applicationId: this.options.applicationId, idempotencyKey: key, correlationId: key, requestId: key, commandId: key, payload: { ...jsonObject(input.input), triggerId: descriptor.id } }); const run = await requiredRun(this.options.execution, receipt.runId); return { created: !receipt.replayed, job: job(run, descriptor) }; }
  async enqueueSchedule(input: EnqueueScheduledTriggerOccurrenceInput): Promise<EnqueueTriggerResult> { const descriptor = await this.define(input.triggerId); const receipt = await this.options.triggers.occur({ triggerId: canonicalId(this.options, descriptor.id), type: "schedule", tenantId: this.options.tenantId, applicationId: this.options.applicationId, idempotencyKey: input.idempotencyKey, correlationId: input.idempotencyKey, requestId: input.idempotencyKey, commandId: input.idempotencyKey, payload: { occurrence: input.availableAt, workflowId: descriptor.workflowId, triggerId: descriptor.id } }); return { created: !receipt.replayed, job: job(await requiredRun(this.options.execution, receipt.runId), descriptor) }; }
  async claim(workerId: string, leaseMs: number): Promise<TriggerJobSnapshot | undefined> { const value = await this.options.execution.claim({ workerId, leaseMs, queues: ["default"] }); if (!value) return undefined; return job(value.run, await this.descriptorFor(value.run)); }
  async get(id: string): Promise<TriggerJobSnapshot> { const run = await requiredRun(this.options.execution, id); return job(run, await this.descriptorFor(run)); }
  async list(filter?: TriggerJobFilter): Promise<TriggerJobSnapshot[]> { const values: TriggerJobSnapshot[] = []; for (const run of await this.options.execution.listRuns()) { const value = job(run, await this.descriptorFor(run)); if ((!filter?.triggerId || value.triggerId === filter.triggerId) && (!filter?.workflowId || value.workflowId === filter.workflowId) && (!filter?.status || (Array.isArray(filter.status) ? filter.status : [filter.status]).includes(value.status))) values.push(value); } return values; }
  async complete(id: string, runId?: string): Promise<TriggerJobSnapshot> { const { run, attempt } = await active(this.options.execution, id); return job(await this.options.execution.complete(run.id, attempt.id, attempt.fencingToken, { ...(runId ? { workflowRunId: runId } : {}) }), await this.descriptorFor(run)); }
  async fail(id: string, error: string, retry: boolean): Promise<TriggerJobSnapshot> { const { run, attempt } = await active(this.options.execution, id); return job(await this.options.execution.fail(run.id, attempt.id, attempt.fencingToken, error, retry), await this.descriptorFor(run)); }
  async cancel(id: string): Promise<TriggerJobSnapshot> { const run = await this.options.execution.cancel(id); return job(run, await this.descriptorFor(run)); }
  async retry(id: string): Promise<TriggerJobSnapshot> { const run = await this.options.execution.retry(id); return job(run, await this.descriptorFor(run)); }
  private async define(id: string): Promise<TriggerDescriptor> { const value = await this.options.getTrigger(id); await this.options.triggers.define({ id: canonicalId(this.options, id), tenantId: this.options.tenantId, applicationId: this.options.applicationId, type: triggerType(value), enabled: value.enabled, target: { sourceType: "workflow", sourceIdTemplate: value.workflowId }, config: jsonObject(value.config ?? {}) }); return value; }
  private async descriptorFor(run: ExecutionRun): Promise<TriggerDescriptor> { const id = typeof run.payload?.triggerId === "string" ? run.payload.triggerId : run.idempotencyKey.split(":")[0]!; return this.options.getTrigger(id.replace(`${this.options.tenantId}:${this.options.applicationId}:`, "")); }
}
function canonicalId(options: { readonly tenantId: string; readonly applicationId: string }, id: string): string { return `${options.tenantId}:${options.applicationId}:${id}`; }
function triggerType(value: TriggerDescriptor): "manual" | "schedule" | "webhook" | "event" { if (value.type === "schedule") return "schedule"; if (value.type === "http" || value.type === "webhook") return "webhook"; if (value.type === "manual") return "manual"; return "event"; }
function jsonObject(value: unknown): import("@dromio/protocols").DromioJsonObject { const parsed = JSON.parse(JSON.stringify(value)) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return { value: parsed as import("@dromio/protocols").DromioJsonValue }; return parsed as import("@dromio/protocols").DromioJsonObject; }
async function requiredRun(service: ExecutionService, id: string): Promise<ExecutionRun> { const value = await service.getRun(id); if (!value) throw new Error(`Execution run ${id} was not found.`); return value; }
async function active(service: ExecutionService, id: string): Promise<{ readonly run: ExecutionRun; readonly attempt: ExecutionAttempt }> { const run = await requiredRun(service, id); const attempt = (await service.listAttempts(id)).at(-1); if (!attempt) throw new Error(`Execution run ${id} has no attempt.`); return { run, attempt }; }
function job(run: ExecutionRun, descriptor: TriggerDescriptor): TriggerJobSnapshot { return { id: run.id, triggerId: descriptor.id, workflowId: descriptor.workflowId, occurrenceId: run.idempotencyKey, idempotencyKey: run.idempotencyKey, status: status(run), attempts: run.attemptCount, maxAttempts: run.maxAttempts, availableAt: run.availableAt, createdAt: run.createdAt, updatedAt: run.updatedAt, ...(run.status === "running" ? { lockedBy: "canonical-execution" } : {}), ...(typeof run.result?.workflowRunId === "string" ? { runId: run.result.workflowRunId } : {}), ...(run.errorCode ? { error: run.errorCode } : {}), payload: { input: run.payload ?? {}, source: "canonical-trigger" } }; }
function status(run: ExecutionRun): TriggerJobSnapshot["status"] { if (run.status === "running") return "claimed"; if (run.status === "waiting") return "running"; if (run.status === "cancelling") return "running"; if (run.status === "cancelled") return "dead"; return run.status; }
