export const WORKFLOW_MCP_APP_URI = "ui://dromio/workflow-run";
export const WORKFLOW_MCP_APP_MIME_TYPE = "text/html;profile=mcp-app";

export function workflowMcpAppHtml(toolPrefix: string): string {
  const prefix = JSON.stringify(toolPrefix);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dromio workflow run</title><style>
:root{color-scheme:light dark;font:14px/1.45 ui-sans-serif,system-ui,sans-serif}body{margin:0;background:var(--color-background-primary,#090b10);color:var(--color-text-primary,#e9edf5)}[hidden]{display:none!important}main{padding:16px;display:grid;gap:12px}.bar,.card{border:1px solid var(--color-border-primary,#293142);border-radius:12px;background:var(--color-background-secondary,#10141d);padding:12px}.bar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.grow{flex:1}.status{font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#8fb2ff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.node{border-left:3px solid #53647f;padding:8px 10px;background:#0b0e15}.node.done{border-color:#39d98a}.node.waiting{border-color:#ffbf69}.node.failed{border-color:#ff6b6b}.muted{color:var(--color-text-secondary,#9aa5b7)}button,input,textarea{font:inherit;border:1px solid #39445a;border-radius:8px;background:#171d28;color:inherit;padding:8px}button{cursor:pointer;background:#26324a}button:hover,button:focus-visible{background:#31405f;outline:2px solid #8fb2ff;outline-offset:2px}textarea{width:100%;min-height:74px;box-sizing:border-box}.quick{display:flex;gap:8px}.quick button{flex:1}.reject{background:#40242c}pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:0;font-size:12px}.actions{display:grid;gap:8px}.error{color:#ff8f8f}.artifacts{display:flex;gap:8px;flex-wrap:wrap}.pill{border:1px solid #39445a;border-radius:999px;padding:4px 8px}@media(max-width:420px){main{padding:10px}.grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}</style></head>
<body><main><section class="bar"><div class="grow"><strong id="title">Workflow run</strong><div class="muted" id="identity">Waiting for tool data…</div></div><span class="status" id="status" aria-live="polite">loading</span><button id="refresh" type="button">Refresh</button></section><section class="grid" id="timeline" aria-label="Workflow graph"></section><section class="card actions" id="actions" hidden><strong id="action-title">Action required</strong><div id="prompt" class="muted"></div><pre id="assignment"></pre><div class="quick" id="question-actions" hidden></div><div class="quick" id="approval-actions" hidden><button id="approve" type="button">Approve</button><button id="reject" class="reject" type="button">Reject</button></div><textarea id="value" aria-label="Structured response" placeholder='Enter JSON, for example {"report":"complete"}'></textarea><button id="submit" type="button">Submit and continue</button><div id="error" class="error" role="alert"></div></section><section class="card"><strong>Artifacts and output</strong><div class="artifacts" id="artifacts"></div><pre id="output"></pre></section></main>
<script>
const prefix=${prefix};const terminal=new Set(["completed","failed","cancelled","exhausted"]);let run=null;let workflow=null;let seq=0;let renderedSignature="";let pollTimer=null;let polling=false;const pending=new Map();
const send=(method,params)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});parent.postMessage({jsonrpc:"2.0",id,method,params},"*")});
const notify=(method,params={})=>parent.postMessage({jsonrpc:"2.0",method,params},"*");
addEventListener("message",event=>{if(event.source!==parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return}if(message.method==="ui/notifications/tool-result")accept(message.params)});
function accept(result){const data=result?.structuredContent||parseText(result?.content);run=data?.run||data?.job?.run||run;workflow=data?.workflow||workflow;if(run){const signature=runSignature(run);if(signature!==renderedSignature){renderedSignature=signature;render()}schedulePoll()}}
function parseText(content){try{return JSON.parse(content?.find?.(item=>item.type==="text")?.text||"null")}catch{return null}}
function runSignature(value){const events=value?.events||[];const last=events.at(-1);return JSON.stringify([value?.runId,value?.status,last?.index,last?.type,(value?.pendingHooks||[]).map(item=>item.token),(value?.pendingQuestions||[]).map(item=>item.id),value?.result,value?.state])}
function stepState(id,events,hook){if(events.some(event=>event.stepId===id&&event.type.includes("failed")))return"failed";if(hook?.stepId===id)return"waiting";if(events.some(event=>event.stepId===id&&event.type.includes("completed")))return"done";if(events.some(event=>event.stepId===id&&(event.type.includes("requested")||event.type.includes("suspended"))))return"waiting";return""}
function render(){document.querySelector("#title").textContent=workflow?.title||run.workflowId||"Workflow run";document.querySelector("#identity").textContent=run.runId;document.querySelector("#status").textContent=run.status;const events=run.events||[];const hook=run.pendingHooks?.[0];const graphSteps=workflow?.graph?.nodes||[];const nodes=graphSteps.length?graphSteps.map(item=>({label:item.label||item.id,detail:item.kind||"step",state:stepState(item.id,events,hook)})):events.slice(-12).map(event=>({label:event.stepId||event.type,detail:event.type+' · #'+event.index,state:event.type.includes("failed")?'failed':event.type.includes("completed")?'done':event.type.includes("requested")||event.type.includes("suspended")?'waiting':''}));document.querySelector("#timeline").innerHTML=nodes.map(node=>'<div class="node '+node.state+'"><strong>'+escapeHtml(node.label)+'</strong><div class="muted">'+escapeHtml(node.detail)+'</div></div>').join("")||'<div class="node waiting">Run created</div>';const question=run.pendingQuestions?.[0];const choices=question?.options||[];const actions=document.querySelector("#actions");actions.hidden=!(hook||question);document.querySelector("#action-title").textContent=question?'Question':hook?.kind==='approval'?'Approval required':hook?.kind==='handoff_requested'?'Delegated work requested':'Action required';document.querySelector("#prompt").textContent=question?.prompt||hook?.title||hook?.input?.summary||hook?.kind||"";document.querySelector("#assignment").textContent=hook?.kind==='handoff_requested'?JSON.stringify({instructions:hook.input?.instructions,context:hook.input?.context,capabilities:hook.input?.capabilities,artifacts:hook.input?.artifacts,outputSchema:hook.input?.outputSchema||hook.schema,workflowId:hook.input?.workflowId,runId:hook.input?.runId,stepId:hook.input?.stepId||hook.stepId},null,2):"";const questionActions=document.querySelector("#question-actions");questionActions.replaceChildren(...choices.map(option=>{const button=document.createElement("button");button.type="button";button.textContent=option.label;button.onclick=()=>answerQuestion(option.value);return button}));questionActions.hidden=!choices.length;document.querySelector("#approval-actions").hidden=hook?.kind!=="approval";document.querySelector("#value").hidden=hook?.kind==="approval"||choices.length>0;document.querySelector("#submit").hidden=hook?.kind==="approval"||choices.length>0;document.querySelector("#value").value="";document.querySelector("#artifacts").innerHTML=(run.artifacts||[]).map(item=>'<span class="pill">'+escapeHtml(item.name||item.kind)+'</span>').join("");document.querySelector("#output").textContent=typeof run.result==="string"?run.result:JSON.stringify(run.result??run.state??{},null,2);size()}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function readValue(){const raw=document.querySelector("#value").value.trim();if(!raw)return "";try{return JSON.parse(raw)}catch{return raw}}
async function call(name,args){document.querySelector("#error").textContent="";try{const result=await send("tools/call",{name:prefix+"."+name,arguments:args});accept(result);if(result?.isError)throw new Error(parseText(result?.content)?.error||"Action failed")}catch(error){document.querySelector("#error").textContent=error.message}}
function schedulePoll(){clearTimeout(pollTimer);if(run&&!terminal.has(run.status))pollTimer=setTimeout(poll,1500)}
async function poll(){if(polling||!run||terminal.has(run.status)||document.hidden)return schedulePoll();polling=true;try{accept(await send("tools/call",{name:prefix+".get_run",arguments:{runId:run.runId}}))}catch{}finally{polling=false;schedulePoll()}}
document.addEventListener("visibilitychange",()=>{if(!document.hidden)schedulePoll()});
function answerQuestion(value){const question=run?.pendingQuestions?.[0];if(question)return call("answer_question",{runId:run.runId,questionId:question.id,value})}document.querySelector("#refresh").onclick=()=>run&&call("get_run",{runId:run.runId});document.querySelector("#submit").onclick=()=>{const question=run?.pendingQuestions?.[0];const hook=run?.pendingHooks?.[0];if(question)return answerQuestion(readValue());if(hook)return call("resume_hook",{token:hook.token,value:readValue(),source:{adapter:"mcp-app",participant:"human",capabilities:hook.input?.capabilityRequirements?.required||[]}})};
function approvalValue(approved){const hook=run?.pendingHooks?.[0];const schema=hook?.schema||{};if(schema.type==="boolean")return approved;if(schema.type==="object"&&schema.properties?.approved?.type==="boolean")return {approved};const choices=Array.isArray(schema.enum)?schema.enum:[];const desired=choices.find(value=>String(value).toLowerCase()=== (approved?"approve":"reject"));return desired??(approved?"approved":"rejected")}
function decide(approved){const hook=run?.pendingHooks?.[0];if(hook)return call("resume_hook",{token:hook.token,value:approvalValue(approved),source:{adapter:"mcp-app",participant:"human"}})}document.querySelector("#approve").onclick=()=>decide(true);document.querySelector("#reject").onclick=()=>decide(false);
function size(){notify("ui/notifications/size-changed",{height:document.documentElement.scrollHeight})}
send("ui/initialize",{appCapabilities:{},appInfo:{name:"Dromio Workflow Run",version:"1.0.0"},protocolVersion:"2026-01-26"}).then(()=>{notify("ui/notifications/initialized");size()});
</script></body></html>`;
}
