import type { DromioThreadEventV1, DromioThreadItemV1, DromioThreadV1, DromioToolCallItem } from "@dromio/protocols";
import { ThreadServiceError, threadNotFound } from "./errors.js";
import type { ThreadIdFactory, ThreadPolicyPort, ThreadServiceClock, ThreadStore, ThreadTransaction } from "./ports.js";
import type { CompleteToolCallInput, StartToolCallInput, ThreadCommandContext, ThreadReceipt, ThreadScope } from "./types.js";
import { persistCommand, replayCommand } from "./idempotency.js";
import { assertExecutionFence } from "./execution-fence.js";
import { correlation, provenance } from "./lineage.js";

export class ThreadToolService {
  constructor(private readonly options: { readonly store: ThreadStore; readonly policy: ThreadPolicyPort; readonly clock: ThreadServiceClock; readonly ids: ThreadIdFactory }) {}
  async start(context: ThreadCommandContext, input: StartToolCallInput): Promise<ThreadReceipt<DromioToolCallItem>> { validateRecovery(input); const scope = fromContext(context); const thread = await this.require(scope, input.threadId); await this.options.policy.authorize({ action: "turn.control", actor: context.actor, scope, thread }); return this.options.store.transaction(async (tx) => { const replay = await replayCommand<DromioToolCallItem>(tx, scope, context, "tool_calls.start", input); if (replay) return replay; let current = await locked(tx, scope, input.threadId); const turn = (await tx.listTurns(input.threadId)).find((value) => value.id === input.turnId); if (!turn || !["running", "waiting_for_approval", "waiting_for_input"].includes(turn.status)) throw new ThreadServiceError({ code: "validation_failed", message: "Tool calls require an active turn." }); const now = this.options.clock.now(); if (context.execution) assertExecutionFence(turn, context, now, "current"); const itemId = input.id ?? this.options.ids.create("item"); const item: DromioToolCallItem = { id: itemId, threadId: current.id, turnId: turn.id, ordinal: current.lastItemOrdinal + 1, createdAt: now, createdBy: context.actor.subject, provenance: { ...provenance(context, { threadId: current.id, turnId: turn.id, itemId }), toolId: input.toolId }, type: "tool_call", toolId: input.toolId, toolVersion: input.toolVersion ?? "unknown", ...(input.capabilityId ? { capabilityId: input.capabilityId } : {}), arguments: input.arguments, effect: input.effect, recoveryPolicy: input.recoveryPolicy, ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), status: input.approvalRequestId ? "waiting_for_approval" : "running", ...(input.approvalRequestId ? { approvalRequestId: input.approvalRequestId } : {}) }; await tx.putItem(item); current = await changed(tx, { ...current, lastItemOrdinal: item.ordinal, version: current.version + 1, updatedAt: now }, context, this.options.ids, this.options.clock, { itemId: item.id, turnId: turn.id, status: item.status }); await tx.putThread(current); const result = receipt(context, item, current.lastSequence); await persistCommand(tx, scope, context, "tool_calls.start", input, result); return result; }); }
  async complete(context: ThreadCommandContext, input: CompleteToolCallInput): Promise<ThreadReceipt<DromioToolCallItem>> { const scope = fromContext(context); const thread = await this.require(scope, input.threadId); await this.options.policy.authorize({ action: "turn.control", actor: context.actor, scope, thread }); return this.options.store.transaction(async (tx) => { const replay = await replayCommand<DromioToolCallItem>(tx, scope, context, "tool_calls.complete", input); if (replay) return replay; let current = await locked(tx, scope, input.threadId); const item = (await tx.listItems(input.threadId)).find((value): value is DromioToolCallItem => value.id === input.itemId && value.type === "tool_call"); if (!item) throw new ThreadServiceError({ code: "resource_not_found", message: `Tool call ${input.itemId} was not found.` }); const turn = item.turnId ? (await tx.listTurns(input.threadId)).find((value) => value.id === item.turnId) : undefined; const now = this.options.clock.now(); if (context.execution && turn) assertExecutionFence(turn, context, now, "current"); const updated: DromioToolCallItem = { ...item, status: input.status, ...(input.result !== undefined ? { result: input.result } : {}), ...(input.artifactIds ? { artifactIds: input.artifactIds } : {}) }; await tx.putItem(updated); current = await changed(tx, { ...current, version: current.version + 1, updatedAt: now }, context, this.options.ids, this.options.clock, { itemId: item.id, turnId: item.turnId ?? "", status: updated.status }); await tx.putThread(current); const result = receipt(context, updated, current.lastSequence); await persistCommand(tx, scope, context, "tool_calls.complete", input, result); return result; }); }
  private async require(scope: ThreadScope, id: string): Promise<DromioThreadV1> { const value = await this.options.store.getThread(scope, id); if (!value) throw threadNotFound(id); return value; }
}
async function changed(tx: ThreadTransaction, thread: DromioThreadV1, context: ThreadCommandContext, ids: ThreadIdFactory, clock: ThreadServiceClock, payload: { readonly itemId: string; readonly turnId: string; readonly status: string }): Promise<DromioThreadV1> { const scope = fromContext(context); const next = { ...thread, lastSequence: thread.lastSequence + 1 }; const event: DromioThreadEventV1 = { schemaVersion: "dromio.thread-event.v1", eventId: ids.create("event"), type: "tool_call.changed", ...scope, threadId: thread.id, sequence: next.lastSequence, applicationSequence: await tx.nextApplicationSequence(scope), timestamp: clock.now(), ...correlation(context), payload }; await tx.appendEvent(event); await tx.appendOutbox({ id: ids.create("outbox"), topic: "thread.events", aggregateId: thread.id, payload: { eventId: event.eventId, type: event.type, ...scope, threadId: thread.id, sequence: event.sequence, applicationSequence: event.applicationSequence }, createdAt: event.timestamp, attempts: 0 }); return next; }
async function locked(tx: ThreadTransaction, scope: ThreadScope, id: string): Promise<DromioThreadV1> { const value = await tx.getThread(id); if (!value || value.tenantId !== scope.tenantId || value.applicationId !== scope.applicationId) throw threadNotFound(id); return value; }
function fromContext(context: ThreadCommandContext): ThreadScope { return { tenantId: context.actor.tenantId, applicationId: context.actor.applicationId }; }
function receipt(context: ThreadCommandContext, resource: DromioToolCallItem, sequence: number): ThreadReceipt<DromioToolCallItem> { return { schemaVersion: "dromio.command-receipt.v1", commandId: context.commandId, resource, threadSequence: sequence, replayed: false }; }
function validateRecovery(input: StartToolCallInput): void { if (input.recoveryPolicy !== "automatic_retry") return; if (input.effect === "non_idempotent") throw new ThreadServiceError({ code: "validation_failed", message: "Non-idempotent tools require manual reconciliation." }); if (input.effect === "idempotent" && !input.idempotencyKey) throw new ThreadServiceError({ code: "validation_failed", message: "Automatically retried idempotent tools require an idempotency key." }); }
